version: '3'
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=myuser
      - MINIO_ROOT_PASSWORD=mypassword
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
