name: Build JAR using Maven Wrapper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

#      - name: Make Maven Wrapper executable
#        run: chmod +x mvnw

      - name: Build JAR
        run: ./mvnw package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-jar
          path: target/twelve-factor-demo-0.0.1-jar-with-dependencies.jar
